import type { Metadata } from "next";
import { notFound } from "next/navigation";

import { ServiceVisual } from "@/components/home/ServiceVisual";
import { PageIntro } from "@/components/layout/PageIntro";
import { PillarCrossNav } from "@/components/services/PillarCrossNav";
import { ButtonLink } from "@/components/ui/Button";
import { Container } from "@/components/ui/Container";
import { primaryCta } from "@/data/navigation";
import { pillarBySlug, SERVICE_PILLAR_SLUGS } from "@/data/service-pillars";
import { cn } from "@/lib/utils";

/**
 * Params are typed by hand rather than with the generated `PageProps<…>`
 * helper: that helper's route union comes from `.next/dev/types/routes.d.ts`,
 * which is regenerated by Next — so on the first `tsc --noEmit` after adding a
 * route the union is still stale and the reference fails. The hand-written type
 * is structurally identical to `ParamsOf<"/services/[slug]">`, and `next build`
 * still validates the page against the real route types.
 */
type PillarPageProps = {
  params: Promise<{ slug: string }>;
};

/**
 * `/services/[slug]` — the four pillar pages the source's route map lists as
 * main routes (`/services/strategy`, `/systems`, `/products`, `/creative`).
 *
 * Every string on this page is already approved elsewhere: the label, the
 * action word, the description and the abstract diagram come from
 * `data/services.ts` (via `data/service-pillars.ts`), and the contents list
 * comes from `data/service-capabilities.ts`. Nothing here is written for this
 * page, and nothing is added to make it look fuller — the source gives each
 * pillar one sentence and a list, so that is what a pillar page holds. The page
 * earns its place by being addressable and by carrying the cross-navigation,
 * not by inventing claims, metrics, clients or case studies.
 *
 * No `border-t`: the navbar already draws the rule above the first block, and
 * every other page on the site follows the same rule.
 */

/** Only the four approved slugs are generated; anything else falls to `notFound()`. */
export function generateStaticParams() {
  return SERVICE_PILLAR_SLUGS.map((slug) => ({ slug }));
}

export async function generateMetadata({ params }: PillarPageProps): Promise<Metadata> {
  const { slug } = await params;
  const pillar = pillarBySlug.get(slug);

  if (!pillar) return {};

  return {
    title: pillar.service.title,
    description: pillar.service.description,
  };
}

export default async function ServicePillarPage({ params }: PillarPageProps) {
  const { slug } = await params;
  const pillar = pillarBySlug.get(slug);

  if (!pillar) notFound();

  const { service, includes } = pillar;
  const dark = service.surface === "dark";

  return (
    <section aria-labelledby="pillar-title">
      <Container className="py-section-lg">
        <PageIntro
          eyebrow={`${service.number} — ${service.action}`}
          titleId="pillar-title"
          title={service.title}
          lead={<p>{service.description}</p>}
        />

        <div className="hv-grid mt-20 items-start gap-y-12">
          <div className="col-span-4 md:col-span-8 lg:col-span-5">
            <h2 className="text-label uppercase text-black/70">Includes</h2>

            <ul className="mt-6 flex flex-col gap-2 border-l border-line pl-5 text-body text-black/75">
              {includes.map((item) => (
                <li key={item}>{item}</li>
              ))}
            </ul>
          </div>

          {/* Same frame and same one-dark-pillar rhythm as the `/services` rows,
              so the two views of the same four pillars stay recognisably one
              system. */}
          <div
            className={cn(
              "col-span-4 border md:col-span-8 lg:col-span-6 lg:col-start-7",
              dark ? "border-black bg-black" : "border-line bg-white",
            )}
          >
            <ServiceVisual kind={service.visual} surface={service.surface} />
          </div>
        </div>

        <div className="mt-20">
          <h2 className="text-label uppercase text-black/70">Four pillars</h2>
          <PillarCrossNav currentSlug={pillar.slug} className="mt-6" />
        </div>

        {/* The source gives one CTA per pillar — "Explore AI Strategy →" — and
            that is the link *into* this page. On the page itself the only honest
            next step is the shared one, so it reuses `primaryCta` rather than
            inventing a per-pillar flow. */}
        <div className="mt-20 border-t border-line pt-12">
          <ButtonLink href={primaryCta.href} arrow>
            {primaryCta.label}
          </ButtonLink>
        </div>
      </Container>
    </section>
  );
}
